// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parent.proto

package com.bok.parent.integration.grpc;

public interface AccountIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 accountId = 1;</code>
   * @return The accountId.
   */
  long getAccountId();
}
