// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parent.proto

package com.bok.parent.integration.grpc;

public interface BooleanOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Boolean)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool value = 1;</code>
     *
     * @return The value.
     */
    boolean getValue();
}
