// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parent.proto

package com.bok.parent.integration.grpc;

public interface EmailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
