// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parent.proto

package com.bok.parent.integration.grpc;

public final class ParentProto {
  private ParentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014parent.proto\"!\n\014EmailRequest\022\021\n\taccoun" +
      "tId\030\001 \001(\004\"\036\n\rEmailResponse\022\r\n\005email\030\001 \001(" +
      "\t23\n\006Parent\022)\n\010GetEmail\022\r.EmailRequest\032\016" +
      ".EmailResponseB0\n\037com.bok.parent.integra" +
      "tion.grpcB\013ParentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmailRequest_descriptor,
        new java.lang.String[] { "AccountId", });
    internal_static_EmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmailResponse_descriptor,
        new java.lang.String[] { "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
