server:
  port: 8080

active-mq:
  users-queue: users
  broker-url: tcp://eureka:61616

spring:
  application:
    name: parent

  activemq:
    packages:
      trusted: com.bok.krypto.model

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://dev.faraone.ovh:3307/parent
    username: developer
    password: password4testing

  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

zuul:
  routes:
    bank:
      path: /bank/**
      serviceId: bank
    krypto:
      path: /krypto/**
      serviceId: krypto

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

jwt:
  security:
    secret: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9090

