active-mq:
  users-queue: users
  broker-url: tcp://dev.faraone.ovh:61616
spring:
  application:
    name: parent
  activemq:
    packages:
      trusted: com.bok.krypto.model
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://dev.faraone.ovh:3307/parent
    username: developer
    password: password4testing
  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9090

security:
  jwt:
    secret: slj35v6845b@d@sidbò#oefuvwdibvsòduvoeubwfeuo8efqb
    expiration: 18000000

