active-mq:
  users-queue: users
  broker-url: tcp://active-mq:61616

spring:
  activemq:
    packages:
      trusted: com.bok.krypto.model
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://parent-db:3306/parentdb
    username: parent
    password: parent
  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey



topology:
  krypto:
    hostname: krypto
    port: 8080

