server:
  port: 8080
  baseUrl: http://dev.faraone.ovh:81

active-mq:
  krypto-users: krypto-accounts
  bank-users: bank-accounts
  broker-url: tcp://activemq:61616
  emails: emails
  bank-account-deletion: bank-account-deletion
  krypto-account-deletion: krypto-account-deletion
  reports: reports
spring:
  application:
    name: parent

  activemq:
    packages:
      trusted: com.bok.krypto.model

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://dev.faraone.ovh:3307/parent
    username: developer
    password: password4testing

  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: mail.faraone.ovh
    username: bok@faraone.ovh
    password: reenterb43{
    from: bok@faraone.ovh

zuul:
  routes:
    bank:
      path: /bank/**
      serviceId: bank
    krypto:
      path: /krypto/**
      serviceId: krypto

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

jwt:
  security:
    secret: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    expiration: 3600
    issuer: bok

minio:
  endpoint: http://s3server
  accessKey: developer
  secretKey: password4testing

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9090

