server:
  port: 8080
  baseUrl: http://dev.faraone.ovh:81

grpc:
  server:
    port: 3030
  client:
    bank:
      address: dns:///bank:3030
      negotiationType: PLAINTEXT
    krypto:
      address: dns:///krypto:3030
      negotiationType: PLAINTEXT

geolocalization:
  databasePath: geolite2-city.mmdb

queues:
  krypto-users: krypto-accounts
  bank-users: bank-accounts
  emails: emails
  bank-account-deletion: bank-account-deletion
  krypto-account-deletion: krypto-account-deletion
  reports: reports

spring:
  application:
    name: parent
  activemq:
    packages:
      trusted:
        - com.bok.parent
        - com.bok.krypto
        - com.bok.bank
        - java.lang
        - java.sql
    user: developer
    password: password4testing
    broker-url: tcp://activemq:61616

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://bok.faraone.ovh:3307/parent
    username: developer
    password: password4testing

  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: smtp.yandex.com
    username: bokdev
    password: ysoccbcojrkafyvt
    from: bokdev@yandex.com
    port: 465
    properties.mail.smtp:
      ssl.enable: true
      auth: true
      starttls.enable: true

zuul:
  routes:
    bank:
      path: /bank/**
      serviceId: bank
    krypto:
      path: /krypto/**
      serviceId: krypto

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

jwt:
  secret: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
  expiration: 3600
  issuer: bok

minio:
  endpoint: s3server
  port: 9000
  secure: false
  accessKey: developer
  secretKey: password4testing

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9090

